#spring.application.name=dubbo-provider
server:
  port: 8100
#应用名称
spring:
  profiles:
    active: dev
  application:
    name: test-app
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatis-test-data?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    initialization-mode: always
    continue-on-error: true
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: SpringBootDemoHikariCP
      max-lifetime: 60000
      connection-timeout: 30000
  dubbo: 
    application:
#注册在注册中心的名称，唯一标识，请勿重复
      id: auth-branch
      name: auth-branch
#注册中心地址，zookeeper集群，启动输出可以看见链接了多个
#单zookeeper服务：zookeeper://127.0.0.1:2181
    registry: 
      address: zookeeper://127.0.0.1:2181?backup=127.0.0.1:2180,127.0.0.1:2182
#暴露服务方式
    protocol:
      id: dubbo
#默认名称，勿修改
      name: dubbo
#暴露服务端口 （默认是20880，修改端口，不同的服务提供者端口不能重复） 
      port: 20881
      status : server
#调用dubbo组建扫描的项目路径
    scan: com.demo.branch.imp  com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.demo.entity




